### ISSUE TITLE
My Site crashes (Google Chrome says: "Aw, Snap!") with I18NConf

### ISSUE THREAD

**Issue by Obiwarn** [yoolab/i18n-conf#2]
Whenever I remove the languages from Router config and place them in my I18NConf. My Site crashes. No errors are displayed.

**Comment by martinopic** [comment]
This is most likely a Iron Router i18n bug (strange, I had a similar behaviour and thought to have fixed the bug). Could you please open a issue [here](https://github.com/yoolab/iron-router-i18n/issues) and show me a meaningful excerpt of your configuration? Thanks.
