### ISSUE TITLE
I18NConf.setLanguage does not change path (but the language)

### ISSUE THREAD

**Issue by Obiwarn** [yoolab/i18n-conf#3]
WWhen I replace Router.setLang with I18NConf version, the language url does not change.

**Comment by martinopic** [comment]
I need more information, try to use the sample app in `examples/basic-i18n-conf` in Iron Router i18n. Using `I18NConf.setLanguage` there does work and change language and url. Also in #4 you are reporting that the url DOES change (what's not changing is the "content").

**Comment by martinopic** [comment]
Please see rewritten examples in iron-router-i18n master. In particulare basic-tap-i18n example. `I18NConf.setLanguage` works perfectly there and changes language, path and content (tap-i18n).
