### ISSUE TITLE
setLanguage + Links error

### ISSUE THREAD

**Issue by Obiwarn** [yoolab/i18n-conf#4]
1. load yoursite.com/en
2. click link "terms": opens /en/terms (i.e. works fine)
3. change language programmatically with a language selection dropdown: I18NConf.setLanguage('fr'): opens yoursite.com/fr/
4. click on a link "terms": still opens url en/terms but displays content of (fr/terms)

**Comment by martinopic** [comment]
What do you mean by "content"? When changing the language the url (and the route) changes, it's up to you whether this should show a different content or not, the router will just be aware of the different language and update the location url and any path/url/link generated with the helpers accordingly.

**Comment by Obiwarn** [comment]
please correct me if I get something wrong but when i follow a link it should be aware of the current language (like in step 2). 
so in step 4. it should open the url fr/terms and not en/terms.

by content I mean that obviously onLanguageChange was called because the pages conent changed to French. but the router was not informed that the language changed.

**Comment by martinopic** [comment]
I've repeated similar steps with iron-router-i18n examples/basic-i18n-conf sample app.

1) Clean all cookies
2) Go to http://localhost:3000
3) Click on "Page two" link (goes to http://localhost:3000/en/two)
4) Programmatically change the language: `I18NConf.setLanguage('it')`, the language change, the url change and so does the "Page Two" link generated with `pathFor` helper showing now `http://localhost:3000/it/due`

I need more information on your configuration or a way to reproduce the behaviour you are experiencing with the sample app.
