### ISSUE TITLE
autoConfLanguage seems to override url language?

### ISSUE THREAD

**Issue by Obiwarn** [yoolab/i18n-conf#5]
when set to true it overrides the url language

e.g. auto lang is en and I open /fr/faq it shows the en content

shouldn't auto conf only work when no language is given in the URL?

**Comment by martinopic** [comment]
Can't repeat this. Try to use the sample app in examples/basic-i18n-conf in Iron Router i18n (just type `meteor` in it and go to `http://localhost:3000`. Assuming you don't have 'es' as the browser default language going to `http://localhost:3000/es/dos` switch the language to `es` even if autoConfLanguage is on.

Maybe I did not understand the behaviour you are reporting, could you try to repeat it on the same example app?

**Comment by martinopic** [comment]
Try to see if new iron-router-i18n 0.5.7 and i18n-conf 0.2.1 solve this problem.

**Comment by Obiwarn** [comment]
My i18n package seems to load language files delayed. So fr was just not ready when fr for  fr/faq was called by the router.
I got it to work by adding a setTimeout.

**Comment by martinopic** [comment]
Where did you exactly added the setTimeout? If you could show me some code maybe I could improve the package not to incur on this problem.

**Comment by Obiwarn** [comment]
Thank you for your time. 

Please be prepared for a horribly hackish solution (written in Coffeescript). However, this works in production on our company site.

My Language setting functions:

```
Language.setUserLanguageDelayed = (lang) ->
    Language.setUserLanguage(lang)
    setLang = ->
        Language.setLanguage(lang)
    setTimeout(setLang, 100) # set language delayed (bug?: en lang files not loaded yet? blaze not ready?)
    setTimeout(setLang, 2000) # even more delayed for slow devices
    return

Language.setLanguage = (lang) ->
    console.log("i18n: setting language " + lang)
    T9n.setLanguage(lang) # accounts t9n (e.g. error msg)
    TAPi18n.setLanguage(lang).done( ->
        Session.set("showLanguageLoader", false)
        HoardSEO.update()
    )
    return
```

My config files:
(Please also see the "default language" bug that I submitted earlier. The default lang en causes a router error message: "No Template named En or en". So my workarounf is to define xx als default language and redirect to en if the user enters a /xx/ url)

```
I18NConf.configure(

    defaultLanguage: 'xx' #BUG default language z.B. 'en' macht error: Cannot find template 'en'
    languages: ['en', 'de', 'fr', 'xx']
)



I18NConf.onLanguageChange( (oldLang, newLang) ->
    console.log("I18NConf router setting new lang: " + newLang);
    if(newLang == 'xx') # bad hack because of above bug
        delay 2000, ->
            I18NConf.setLanguage('en')
            Router.go('/')

    else
        if(Language?)
            Language.setUserLanguageDelayed(newLang)
)
```

**Comment by martinopic** [comment]
I've just pushed a sample iron-routeri18n / tap-i18n integration app in master (https://github.com/yoolab/iron-router-i18n/tree/1.x/examples/basic-tap-i18n) and it seems to be working seamlessly without al this complication (including the defaultLang hack).

I just can think about some kind of race condition I don't see (but tap-i18n helpers are reactive anyway so the content should change once the files are loaded) or some other thing specific of your app. Can you please try the sample app and see if it works for you too? I'll try to investigate more.

**Comment by martinopic** [comment]
I think we can close this as it was probably related to https://github.com/yoolab/iron-router-i18n/issues/70.
